// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221215141536_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Models.FavoriteProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("FavoriteProducts");
                });

            modelBuilder.Entity("Database.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Database.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Сost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Для новичков. Первое занятие бесплатно",
                            ImagePath = "FreeClasses.jpg",
                            Name = "Бесплатное занятие",
                            Сost = 1m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Разовое посещение без абонемента",
                            ImagePath = "ProductMainImage.jpg",
                            Name = "Разовое посещение",
                            Сost = 300m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Всегда сможем договориться об удобных для вас условиях. \r\nЦена зависит от вида деятельности и количества арендуемых часов. От 100 рублей в дневное время.\r\n\r\nГотовые помещения 70, 55 и 35 (автономный) кв. м для вашего бизнеса.\r\nПлатите только за те часы, которыми\r\nпользуетесь.\r\n\r\nПРИМЕНЕНИЕ\r\n\r\nБерут для:\r\n-Уроков танцев, йоги, фитнеса;\r\n -Мастер - классов по рукоделию;\r\n -Корпоративов, спектаклей;\r\n -Настольных игр;\r\n -Уроков гитары, пианино;\r\n -Офиса, презентаций;\r\n -Вечеринок.",
                            ImagePath = "RentImage.jpg",
                            Name = "Аренда зала",
                            Сost = 100m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Абонемент на 10 уроков, бессрочный. При постоянном посещеении действуют скидки",
                            ImagePath = "ProductMainImage.jpg",
                            Name = "Абонемент на 10 уроков",
                            Сost = 2200m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Абонемент на 10 уроков для пары, бессрочный. При постоянном посещеении действуют скидки",
                            ImagePath = "ProductMainImage.jpg",
                            Name = "Абонемент для пары на 10 уроков",
                            Сost = 4000m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Абонемент на 10 уроков для cтудентов и пенсионеров, бессрочный. При постоянном посещеении действуют скидки",
                            ImagePath = "ProductMainImage.jpg",
                            Name = "Специальные 10 уроков(студенты и пенсионеры)",
                            Сost = 2000m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Проход на любую вечеринку нашего клуба.",
                            ImagePath = "ProductMainImage.jpg",
                            Name = "Вечеринки",
                            Сost = 300m
                        });
                });

            modelBuilder.Entity("Database.Models.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("Database.Models.StorageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<Guid?>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageId");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("Database.Models.UserDeliveryInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("UserDeliveryInfos");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Comment = "",
                            Email = "test@gmail.com",
                            Name = "Lena",
                            PhoneNumber = "123456789"
                        });
                });

            modelBuilder.Entity("Database.Models.FavoriteProduct", b =>
                {
                    b.HasOne("Database.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Database.Models.Order", b =>
                {
                    b.HasOne("Database.Models.UserDeliveryInfo", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.StorageItem", b =>
                {
                    b.HasOne("Database.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("Database.Models.Product", "Product")
                        .WithMany("StorageItems")
                        .HasForeignKey("ProductId");

                    b.HasOne("Database.Models.Storage", "Storage")
                        .WithMany("Items")
                        .HasForeignKey("StorageId");

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("Database.Models.UserDeliveryInfo", b =>
                {
                    b.HasOne("Database.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("Database.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Database.Models.Product", b =>
                {
                    b.Navigation("StorageItems");
                });

            modelBuilder.Entity("Database.Models.Storage", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
